name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - run: npm run lint
      - run: npm run format:check || true
      - run: npm run test:coverage
      - run: npm run analyze:quality || true
      - run: npm run cleanup:orphaned || true
      - run: npm run identify:unused || true
      - run: npm run improve:coverage || true
      - run: npm run audit || true
      - run: npm run outdated || true
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
      - name: Block on test/lint failure
        if: failure()
        run: exit 1

  package:
    needs: build-test-lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Compile
      run: npm run compile

    - name: Create VSIX package
      run: npm run package

    - name: Upload VSIX package
      uses: actions/upload-artifact@v3
      with:
        name: extension-package
        path: "*.vsix"
